# Generated by Django 5.0.7 on 2024-08-14 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
